--- #YAML:1.0
name:               Perl6-Form
version:            0.005
abstract:           Implements the Perl 6 'form' built-in
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:           5.008001
    Perl6::Export:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
